### ISSUE TITLE
missing files in v2.16.0

### ISSUE THREAD

**Issue by eweseongyeoh** [chrvadala/transformation-matrix#100]
Hi, we notice that in v2.16.0 the `build-commonjs` and `build-umd` folder are no longer included in the package however they are still reference in the `package.json` resulting in errors. Could someone help to take a look into the issue?

v2.16.0
<img width="918" alt="Screenshot 2024-02-22 at 5 10 58 PM" src="https://github.com/chrvadala/transformation-matrix/assets/153052961/f3bca457-932b-4a8c-b60d-2158706d490e">

v2.15.0
<img width="873" alt="Screenshot 2024-02-22 at 5 05 46 PM" src="https://github.com/chrvadala/transformation-matrix/assets/153052961/29d9d0d3-5292-46a8-8743-bde2dd7cac8b">

**Comment by chrvadala** [comment]
Fixed with 1.16.1

I don't know when, but looks like that npm removed wildcard support on `files` list 
https://github.com/chrvadala/transformation-matrix/compare/v2.16.0...v2.16.1
