### ISSUE TITLE
2.16.0 is missing build folders build-commonjs/, build-umd/.

### ISSUE THREAD

**Issue by motherthestate** [chrvadala/transformation-matrix#101]
`Error: Cannot find package '.../node_modules/transformation-matrix/package.json' imported from '...'
`

The package.json "main" points to a missing build folder.

Love the library btw <3

**Comment by chrvadala** [comment]
It seems a bug with the release pipeline. I'll release hotfix.

**Comment by chrvadala** [comment]
Fixed with 1.16.1. 

I don't know when, but looks like that npm removed wildcard support on `files` list 
https://github.com/chrvadala/transformation-matrix/compare/v2.16.0...v2.16.1
