### ISSUE TITLE
fromString method and negativeValues

### ISSUE THREAD

**Issue by nbob** [chrvadala/transformation-matrix#11]
When I'am trying to use `fromString` method with negative element in any position I am getting an error `Error: 'matrix(0,1,0,1,0,-1)' is not a matrix`.

You may see an example [here](https://runkit.com/embed/ux2wi5qez4fc)

**Comment by chrvadala** [comment]
You are right. The Regex doesn't consider negative values https://github.com/chrvadala/transformation-matrix/blob/master/src/fromString.js#L5
I will fix it soon

**Comment by nbob** [comment]
Great!
Thanks for response.

**Comment by chrvadala** [comment]
Fixed with 1.6.1
