### ISSUE TITLE
Using the transformation-matrix library in an Angular 4 project

### ISSUE THREAD

**Issue by jonpc2018** [chrvadala/transformation-matrix#14]
Installing the transformation-matrix library in an Angular 4 project, the rotate method seems to be missing the extra parameters, cx & cy

The method is defined as..
rotate(angle, [cx], [cy]) ⇒ Object
Calculate a rotation matrix

and the transformation-matrix.d.ts file contains...
declare module 'transformation-matrix/rotate' {
+  /** Calculate a rotation matrix */
+  export function rotate(angle: number): Matrix;
+  /** Calculate a rotation matrix with a DEG angle */
+  export function rotateDEG(angle: number): Matrix;
+}

**Comment by chrvadala** [comment]
@forabi could you take care of this?

**Comment by chrvadala** [comment]
Fixed with 1.10
