### ISSUE TITLE
Export types Matrix and Point

### ISSUE THREAD

**Issue by jawadst** [chrvadala/transformation-matrix#16]
We are having issues with Webpack packaging a library that depends on `transformation-matrix` (https://github.com/swimlane/ngx-graph/issues/67).

Webpack seems to ignore the `Matrix` type as it is not exported in https://github.com/chrvadala/transformation-matrix/blob/master/transformation-matrix.d.ts whereas it is used by functions that are themselves exported. We end up with type definitions that reference `Matrix` without it being declared anywhere.

Can you export that type as well as `Point`? (I am not using `Point` but I guess it has the same problem)

Thanks for the library, by the way!

**Comment by forabi** [comment]
> Webpack seems to ignore the Matrix type as it is not exported in /transformation-matrix.d.ts@master

Sorry, I don't follow. What does webpack have to do with TypeScript types? Webpack never sees TypeScript. It's `ts-loader`'s job to convert TypeScript to JavaScript which Webpack then processes. 

I don't think your diagnosis of the issue is correct.

**Comment by jawadst** [comment]
@forabi True, I am not accurate there, the TypeScript compiler is the one generating the declarations file and not Webpack.

Does that change the principle that a type used by an exported function should be exported itself?
(for instance, the exported method `applyToPoint` uses the non-exported type `Matrix`)

One simple use case is using the types themselves in my TypeScript code. For instance, today I can do:
```javascript
import { identity } from 'transformation-matrix';

const matrix = identity();
```

but I cannot do:

```javascript
import { identity, Matrix } from 'transformation-matrix';

let matrix: Matrix;
matrix = identity();
```

**Comment by forabi** [comment]
```typescript
import { identity, Matrix } from 'transformation-matrix';

let matrix: Matrix;
matrix = identity();

```
I see. I'll submit a PR soon to expose the types. In the meantime, if you are using TS 2.8, you could do:

```typescript

import { identity } from 'transformation-matrix';

let matrix: ReturnType<typeof identity>;
matrix = identity();
```

**Comment by jawadst** [comment]
I didn't know that option, I'll give it a try.

Thanks for your help!

**Comment by chrvadala** [comment]
Hi @forabi,
how is going?
Are there any news on this?
