### ISSUE TITLE
applying a scale transformation and keeping the element centered

### ISSUE THREAD

**Issue by dagda1** [chrvadala/transformation-matrix#40]
I would be grateful if you could help me understand the maths with regards to applying a scale and keeping the element centred.

I want to apply a scale and also keep the element centred, if I only apply a scale at elements `a` and `d` of the affine matrix then I get [this effect](http://jsfiddle.net/dagda1/funpxytq/).

What I want is [this effect](http://jsfiddle.net/dagda1/1af6L8ox/) with the element remaining centred.

I've been looking at the code in [react-svg-pan](https://github.com/chrvadala/react-svg-pan-zoom) and I don't quite understand how they achieve this.

The first thing they do is call this function:

```
export const getSVGPoint = (value: Matrix, viewerX: number, viewerY: number) => {
  const matrix = fromObject(value);

  const inverseMatrix = inverse(matrix);

  return applyToPoint(inverseMatrix, { x: viewerX, y: viewerY });
};

// const svgPoint = getSVGPoint(matrix, width / 2, height / 2);
```

Why is the inverse of the matrix found?  How does this help find the elements point from the midpoint of the element?

The code then uses the `x` and `y` coordinates of the point to create a new matrix from this code:
```
const matrix = transform(
    fromObject(current),
    translate(SVGPointX, SVGPointY),
    scale(scaleFactor, scaleFactor),
    translate(-SVGPointX, -SVGPointY)
  );
```

The only bit above I understand is the scale part.  I don't understand what the `fromObject` and the 2 `translate` calls do.

I would be grateful for an explanation.

**Comment by dagda1** [comment]
would it possible to get an explanation please?

**Comment by chrvadala** [comment]
I'm going to close this issue. Feel free to open it again.
