### ISSUE TITLE
Add a fromTriangles function

### ISSUE THREAD

**Issue by SophiaLi1** [chrvadala/transformation-matrix#41]
I will provide a PR for this function soon if you don't mind. @chrvadala maybe you can add me as a collaborator so I can create one :)

**Comment by chrvadala** [comment]
Hi Sophia, any PR is great and helps this library to grow.
Feel free to submit a PR covered by tests and some book references where we can validate the algorithm. Don't mind about the documentation. I'll update it as soon as this new feature is ready.
LMK

**Comment by SophiaLi1** [comment]
Thanks! Check out my PR. It's my first time using GitHub, so I hope everything went well.

**Comment by chrvadala** [comment]
Released with 1.15.0
