### ISSUE TITLE
index.js missing export fromTriangles

### ISSUE THREAD

**Issue by yofreke** [chrvadala/transformation-matrix#46]
does exist:

- `node_modules/transformation-matrix/build-commonjs/fromTriangles.js` 
- `require('transformation-matrix/build-commonjs/fromTriangles').fromTriangles`

does not exist:

- `require('transformation-matrix').fromTriangles`

**Comment by chrvadala** [comment]
You're right. 
@SophiaLi1 Could you fix this?

**Comment by chrvadala** [comment]
fixed with 1.15.2
