### ISSUE TITLE
Return type of fromTransformAttribute should be MatrixDescriptor[]

### ISSUE THREAD

**Issue by estollnitz** [chrvadala/transformation-matrix#63]
The return type of `fromTransformAttribute()` is incorrectly specified as `Matrix[]` when it should be `MatrixDescriptor[]`. This causes errors when using the function in TypeScript.

Lines that need changing include:
- https://github.com/chrvadala/transformation-matrix/blob/06321d456325f39dce67f62a3f512762ccdccc6e/src/fromTransformAttribute.js#L7
- https://github.com/chrvadala/transformation-matrix/blob/06321d456325f39dce67f62a3f512762ccdccc6e/transformation-matrix.d.ts#L233
- https://github.com/chrvadala/transformation-matrix/blob/06321d456325f39dce67f62a3f512762ccdccc6e/transformation-matrix.d.ts#L246

**Comment by chrvadala** [comment]
Fixed with v2.2 by @estollnitz
