### ISSUE TITLE
Type definitions for applyToPoint and applyToPoints should accept arrays

### ISSUE THREAD

**Issue by estollnitz** [chrvadala/transformation-matrix#64]
The current type definitions specify that `applyToPoint()` requires a `Point` and `applyToPoints()` requires a `Point[]`. This is more restrictive than the actual implementations, which also allow `[number, number]` and `[number, number][]`, respectively.

One way to fix this is to include a union of types in the function signatures, similar to what was done for `fromTriangles()` here:
https://github.com/chrvadala/transformation-matrix/blob/06321d456325f39dce67f62a3f512762ccdccc6e/transformation-matrix.d.ts#L168

Perhaps a better way would be to change the definition of `Point` to include object and array forms, if the intention is to support both forms everywhere. I'm suggesting something like this:
```
  type Point = { x: number; y: number } | [number, number];
```
The change would go here:
https://github.com/chrvadala/transformation-matrix/blob/06321d456325f39dce67f62a3f512762ccdccc6e/transformation-matrix.d.ts#L11 

If this change is made, the function signature for `fromTriangles()` can be simplified.

**Comment by chrvadala** [comment]
Fixed with v2.2 by @estollnitz
