### ISSUE TITLE
Type definitions for transform and compose should accept a single Matrix[]

### ISSUE THREAD

**Issue by estollnitz** [chrvadala/transformation-matrix#65]
The implementations of `transform()` and `compose` currently accept either multiple `Matrix` parameters or a single `Matrix[]` parameter. Unfortunately, the current type definitions do not cover the case of a single `Matrix[]` parameter. This requires TypeScript code to be written as `transform(...fromDefinition(arrayOfDefinitions))`  when in fact, the `...` should be uneccessary.

I propose adding the following overloads without `...`:
```
  export function transform(matrices: Matrix[]): Matrix;
  export function compose(matrices: Matrix[]): Matrix;
```
These would appear adjacent to the following lines:
- https://github.com/chrvadala/transformation-matrix/blob/06321d456325f39dce67f62a3f512762ccdccc6e/transformation-matrix.d.ts#L136
- https://github.com/chrvadala/transformation-matrix/blob/06321d456325f39dce67f62a3f512762ccdccc6e/transformation-matrix.d.ts#L143

And the documentation can be improved by changing the parameter description as follows:
```
 * @param matrices {...Matrix | Matrix[]} Matrices listed as separate parameters or in an array
```
- https://github.com/chrvadala/transformation-matrix/blob/06321d456325f39dce67f62a3f512762ccdccc6e/src/transform.js#L3
- https://github.com/chrvadala/transformation-matrix/blob/06321d456325f39dce67f62a3f512762ccdccc6e/src/transform.js#L39

**Comment by chrvadala** [comment]
Fixed with v2.2 by @estollnitz
