### ISSUE TITLE
Point union in typescript is not helpful

### ISSUE THREAD

**Issue by dagda1** [chrvadala/transformation-matrix#69]
Hi,

I have just upgraded to the latest version and the type definition for `Point` has changed to a union which is not helpful.

`type Point = { x: number; y: number } | [number, number];`

For every union that is created, I have to use type narrowing to determine what it is if the inference cannot work it out.

It was perfect before:

`type Point = { x: number; y: number }`

I would have a new type for the tuple.

Would you be open to a PR that reverted this?

**Comment by chrvadala** [comment]
Points can be defined as object or array.  The previous version didn't cover both cases.

**Comment by formatlos** [comment]
I've have already created a PR #67 to tackle this issue a fews ago.

**Comment by dagda1** [comment]
@formatlos sir, that is the correct answer.  Bravo!

**Comment by chrvadala** [comment]
PR 67 has been merged and released with version 2.3.0. I hope that it helps ;)
