### ISSUE TITLE
accept CSS/SVG shorthand notation

### ISSUE THREAD

**Issue by derhuerst** [chrvadala/transformation-matrix#8]
What do you think about supporting shorthand notations like `scale(.5)` in addition to `scale(.5, .5)`? Would you mind a PR or would you like to keep this lib unrelated to web stuff?

**Comment by chrvadala** [comment]
Hi @derhuerst, it's absolute useful.

My next goal on this project is to expand the `fromString` feature and make a more generic `parse` 
 function that is able to parse any arbitrary `transform` attribute https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform 
The result of this parser will be a list of operations, also in shorthand notations.
If we add the shorthand notations support on each function we will be able to use those function to evaluate this list and generate a single equivalent matrix as result.
I think that its could be absolute useful.

If you have enough time to add shorthand notation a PR would be accepted.

**Comment by derhuerst** [comment]
[As there already is a parser](https://www.npmjs.com/package/svg-transform-parser), I'd rather focus on supporting an array of transforms, so that people don't need to loop over and apply individually.

**Comment by chrvadala** [comment]
I didn't know that project. It seems able to parse a transformation string. I will test it soon, but I don't like to use it as dependency.
To merge more transformation matrix into a single one there is already available the method `transform` https://github.com/chrvadala/transformation-matrix#transform

**Comment by derhuerst** [comment]
> I didn't know that project. It seems able to parse a transformation string. I will test it soon, but I don't like to use it as dependency.

My point was not to reinvent the wheel be writing another parser, rather depend on other libs to do this job.

**Comment by chrvadala** [comment]
You're right, but consider that this library is reinventing the wheel in ES6 😄 

So I see that svg-transform-parser library uses pegjs as metalanguage and recent version of pegjs supports ES6 (https://github.com/pegjs/pegjs/pull/481). I was able to use that metadescriptor to generate an es6 compliant parser.

I've opened an issue to the author's of that library https://github.com/nidu/svg-transform-parser/issues/1

If he agree we could import that descriptor and include an es6 parser.
After that we have to: 
- complete that descriptor to support some missing syntax like scaleX(2), scaleY(0.5)
- introduce a function that return the parse result as list of matrices
- provide some tests

**Comment by chrvadala** [comment]
Hi @derhuerst,
Are there any news about your PR?
I need it to complete this other PR https://github.com/chrvadala/transformation-matrix/pull/9
Let me know
Thanks ;)

**Comment by derhuerst** [comment]
Hm. Currently, I don't have time to submit a PR, sorry.

**Comment by chrvadala** [comment]
Ok ;) No problem. I will work on it ;)

**Comment by chrvadala** [comment]
Released v1.6.0
