### ISSUE TITLE
Support rotateX, rotateY and rotateZ

### ISSUE THREAD

**Issue by moklick** [chrvadala/transformation-matrix#80]
I would be nice if one could do:

```javascript
const matrixDescription = fromTransformAttribute(
  'rotateX(45deg) rotateY(0deg) rotateZ(45deg)'
);
```

or is this already possible in another way?

**Comment by moklick** [comment]
I guess this is 3D matrix manipulation .. I will close the issue

**Comment by franckOL** [comment]
Looking for  3D matrix manipulation...
