### ISSUE TITLE
'matrix(0.707 0.409 -0.707 0.409 0 0)' is not a matrix

### ISSUE THREAD

**Issue by parkerisme** [chrvadala/transformation-matrix#86]
fromString('matrix(0.707 0.409 -0.707 0.409 0 0)') not support 'matrix(0.707 0.409 -0.707 0.409 0 0)' is not a matrix

**Comment by chrvadala** [comment]
`fromString` method doesn't accept this matrix format, but it needs that any item is separated by a comma. 
For more sophisticated transformations, I suggest you to make use of the other available method : `fromTransformAttribute`

expect(fromTransformAttribute('matrix(0.707, 0.409, -0.707, 0.409, 0, 0)')).toEqual([{ a:0.707, b:0.409, c:-0.707, d:0.409, e:0, f:0, type: "matrix" }])
