### ISSUE TITLE
Optimize parsing performance

### ISSUE THREAD

**Issue by janryWang** [chrvadala/transformation-matrix#91]
Can we parse matrices with normal regular expressions? Now using PEG, the performance is relatively poor

**Comment by chrvadala** [comment]
For basic matrices you can use this method https://github.com/chrvadala/transformation-matrix/blob/main/docs/api.md#fromString, but if you're looking to advanced parsing features you need something like PEG.
Anyway, quite soon I will merge this PR https://github.com/chrvadala/transformation-matrix/pull/89 that uses a new PEG version that should be faster.
