### ISSUE TITLE
Rotate 90 degrees with coordinate = 0

### ISSUE THREAD

**Issue by andreyselin** [chrvadala/transformation-matrix#96]
Hey!

This is probably not library-related issue, but I supposed there was a way to handle it in the library.

Check out the output of the following code.
It is expected that it would be { x: 0, y: 10 }.

```
const {rotate, applyToPoint} = require('transformation-matrix')
const matrix = rotate(Math.PI/2);
const result = applyToPoint(matrix, {x: 10, y: 0});
// { x: 6.123233995736766e-16, y: 10 }
```
Is there a hint allowing getting correct 90 degrees rotation value for coordinates having 0 value?
Thank you!

**Comment by chrvadala** [comment]
Hello, 
`6.123233995736766e-16` it's almost zero, but it isn't zero due to the javascript number precision management, anyway,
you can round a transformation matrix with the `smoothMatrix(m)` function.

See below a working snippet

````
const {rotate, applyToPoint, smoothMatrix} = require('transformation-matrix')
const matrix = rotate(Math.PI/2);
const matrix2 = smoothMatrix(matrix)
const result = applyToPoint(matrix2, {x: 10, y: 0});
// {x: 0, y: 10}
````
